"""baseline schema: clients, sessions, action_items

Revision ID: 9a8591d33449
Revises: 
Create Date: 2026-08-25 22:43:26.723769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a8591d33449'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.Column('session_date', sa.String(), nullable=True),
    sa.Column('next_session_date', sa.String(), nullable=True),
    sa.Column('pain', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('why_now', sa.Text(), nullable=True),
    sa.Column('tried', sa.Text(), nullable=True),
    sa.Column('cost_scale', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('technique', sa.Text(), nullable=True),
    sa.Column('goal_1', sa.String(), nullable=True),
    sa.Column('goal_2', sa.String(), nullable=True),
    sa.Column('goal_detail', sa.Text(), nullable=True),
    sa.Column('goal_why', sa.Text(), nullable=True),
    sa.Column('work_what', sa.Text(), nullable=True),
    sa.Column('work_stop', sa.Text(), nullable=True),
    sa.Column('progress_review', sa.Text(), nullable=True),
    sa.Column('win', sa.Text(), nullable=True),
    sa.Column('obstacles', sa.Text(), nullable=True),
    sa.Column('goal_shift', sa.Text(), nullable=True),
    sa.Column('session_focus', sa.Text(), nullable=True),
    sa.Column('cadence', sa.String(), nullable=True),
    sa.Column('excited', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_table('action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_items_id'), 'action_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_items_id'), table_name='action_items')
    op.drop_table('action_items')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
